name: Successfull merge pipeline

on:
  workflow_dispatch:
  push:

jobs:
    my-reusable:
        uses: Piasecki-grid/grid-capstone-reusable-workflows/.github/workflows/merge-pipeline.yml@main
        secrets:
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
            YOUR_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            K8S_GITHUB_TOKEN: ${{ secrets.K8S_GITHUB_TOKEN }}
        with:
            ACR_NAME: ${{ vars.ACR_NAME }}
            GITHUB_SHA: ${{ github.sha }}