name: Successfull merge pipeline

on:
  workflow_dispatch:
  push:

jobs:
    my-reusable:
        uses: Piasecki-grid/grid-capstone-reusable-workflows/.github/workflows/merge-pipeline.yml@v1.0
        secrets:
            AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
            AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
            AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
            AZURE_CLIENT_SECRET: ${{ vars.AZURE_CLIENT_SECRET }}
            GITHUB_TOKEN: ${{ vars.GITHUB_TOKEN }}
            K8S_GITHUB_TOKEN: ${{ vars.K8S_GITHUB_TOKEN }}
        with:
            ACR_NAME: ${{ vars.ACR_NAME }}
            GITHUB_SHA: ${{ github.sha }}