name: Successfull merge pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.29.0'  
        id: install
      

      - uses: actions/checkout@v4
        name: Checkout code

      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java}}
          distribution: 'temurin'
          cache: maven

      - name: Add executable permissions
        run: chmod a+x mvnw

      - name: Maven install dependencies
        run: ./mvnw clean install package

      # - name: Upload JAR artifact 
      #   uses: actions/upload-artifact@4
      #   with:
      #     name: grid-capstone
      #     path: ./target/*.jar



      - name: Login to ACR
        uses: docker/login-action@v3
        with:

          registry: ${{ vars.ACR_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      
      - name: Docker Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            grid-capstone-${{ github.sha }}



          
      - uses: azure/login@v2
        name: Azure Login
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      
      - name: Getting access to the cluster
        run: |
          az aks get-credentials --resource-group grid-capstone --name dev-grid-cluster --admin --overwrite-existing
          kubectl get pods
          kubectl get nodes
          
            
      
      
