name: Setup cloud infrastructure

on:
  workflow_dispatch:

jobs:
  infrastructure:
    runs-on: ubuntu-latest  
    steps:  
      - uses: azure/login@v2
        name: Azure Login
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setting up terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.29.0'  
        id: install


      - name: Deploy new version of an image to the cluster
        run: |
          az aks get-credentials --resource-group grid-capstone --name dev-grid-cluster --admin --overwrite-existing
          export KUBE_CONFIG_PATH=~/.kube/config

          
      - name: Setup git configuration
        run: |
          git config --global user.name 'Kacper Piasecki'
          git config --global user.email 'k.r.piasecki2@gmail.com'

      - name: Clone git repository of infrastructure
        run: |
          rm -Rf .git
          mkdir cicd
          cd cicd
          git clone https://x-access-token:${{ secrets.INFRA_GITHUB_TOKEN }}@github.com/Piasecki-grid/grid-capstone-terraform-infra.git


      - name: Create resources for remote backend
        run: |
          az group create --name tfstate-rg --location eastus

          az storage account create \
            --name tfstatestorageaccount25 \
            --resource-group tfstate-rg \
            --location eastus \
            --sku Standard_LRS \
            --kind StorageV2

          az storage container create \
            --name tfstate \
            --account-name tfstatestorageaccount25
          
      - name: Terraform Init
        run: |
          cd cicd/grid-capstone-terraform-infra
          terraform init

          
      - name: Terraform Validate
        run: |
          cd cicd/grid-capstone-terraform-infra
          terraform validate
          terraform fmt

      - name: Refactor changes push
        run: |
          cd cicd/grid-capstone-terraform-infra
          git add *.tf
          git commit -am 'Refactored syntax and structure in .tf files'
          git push
        continue-on-error: true

      - name: Terraform Apply
        run: |
          cd cicd/grid-capstone-terraform-infra
          terraform apply --auto-approve
            
      
      
